name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  linkChecker:
    if: github.repository_owner == 'AntonPalmqvist'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress './deploy/**/*.json'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
